# Generated by Django 5.2.7 on 2025-10-22 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveChat', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='matches.match'),
        ),
    ]
