# Generated by Django 5.2.7 on 2025-10-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveChat', '0002_alter_group_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['createdAt']},
        ),
    ]
