# Generated by Django 5.2.7 on 2025-10-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveChat', '0003_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-createdAt']},
        ),
    ]
