# Generated by Django 5.2.7 on 2025-10-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveChat', '0004_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'get_latest_by': 'createdAt', 'ordering': ['createdAt']},
        ),
    ]
