# Generated by Django 5.2.5 on 2025-10-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_chat_groups_customuser_favorite_sport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='chat_groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='matches_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='threads_created',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='venues_booked',
        ),
    ]
